Disable-GameBarTips
Disable-MicrosoftUpdate
Disable-UAC
Disable-BingSearch
Enable-RemoteDesktop
Set-StartScreenOptions -EnableBootToDesktop -EnableDesktopBackgroundOnStart
Set-ExplorerOptions -showFileExtensions -showHiddenFilesFoldersDrives -showProtectedOSFiles
cinst aria2 ccleaner ffmpeg -y